- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
    - name: Read users from CSV file and return a dictionary
      read_csv:
        path: /mnt/d/cloud-devops/ansible/aws-ansible/users.csv
      register: userlist
    
#    - name: create IAM groups
#      iam:
#        iam_type: group
#        name: '{{ group.group }}'
#        state: present
    - name: Create IAM Users
      iam:
        iam_type: user
        name: "{{ user.name }}"
        password: "{{ user.password }}"
        state: present
        groups: "{{ user.group }}"
#        access_key_state: create
  
#    - debug:
#        msg: >-
#          {{ user.name }} and password is {{ user.password }} and group is {{
#          user.group }}
      loop: "{{ userlist.list }}"
      loop_control:
        loop_var: user
       
