---
- name: Read group from CSV file and return a dictionary
  read_csv:
    path: /mnt/d/cloud-devops/ansible/aws-ansible/groups.csv
  register: grouplist
    
- name: create IAM groups
  iam:
    iam_type: group
    name: "{{ group.groupname }}"
    state: present
  loop: "{{ grouplist.list }}"
  loop_control:
    loop_var: group
  register: new_groups  
      
       