# Type: Ansible Playbook Task
# Purpose: To Create an AWS Users and associate then with Existing Group automated way by reading CSV file through Ansible
# Date & Time: June 14, 2022 
# Author: Praful Patel
# ------------------------------------------
---
- name: Read users from CSV file and return a dictionary
  read_csv:
    path: /mnt/d/cloud-devops/ansible/aws-ansible/01-aws-ansible-iam-create/users.csv
  register: userlist
    

- name: Create IAM Users in aws cloud
  iam:
    iam_type: user
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    state: present
    groups: "{{ user.group }}"
  loop: "{{ userlist.list }}"
  loop_control:
    loop_var: user
       
